# 局部规划器DWA(local planner DWA)
DWAPlannerROS:
  # Robot Configuration Parameters 
  max_vel_x: 0.1  # x方向最大线速度绝对值，单位:米/秒(absolute value of maximum linear velocity along x direction. unit:m/s)
  min_vel_x: -0.1 # x方向最小线速度绝对值，负数代表可后退，单位:米/秒(absolute value of minimum linear velocity along x direction. unit:m/s)
  max_vel_y: 0.0   # y方向最大线速度绝对值，单位:米/秒。差分驱动机器人为0(absolute value of maximum linear velocity along y direction, unit:m/s. For differential drive robot, it is 0)
  min_vel_y: 0.0   # y方向最小线速度绝对值，单位:米/秒。差分驱动机器人为0(absolute value of minimum linear velocity along y direction, unit:m/s. For differential drive robot, it is 0)
  max_vel_trans: 0.1      # 机器人最大平移速度的绝对值，单位为 m/s(absolute value of robot's maximum translation velocity, unit:m/s)
  min_vel_trans: 0.05     # 机器人最小平移速度的绝对值，单位为 m/s 不可为零(absolute value of robot's minimum translation velocity, unit:m/s)
  max_vel_theta: 0.5       # 机器人的最大旋转角速度的绝对值，单位为 rad/s(absolute value of robot's maximum rotation angular velocity, unit:rad/s)
  min_vel_theta: 0.1       # 机器人的最小旋转角速度的绝对值，单位为 rad/s(absolute value of robot's minimum rotation angular velocity, unit:rad/s)
  acc_lim_x: 2.5           # 机器人在x方向的极限加速度，单位为 meters/sec^2(robot's extreme acceleration along x direction, unit: meters/sec^2)
  acc_lim_theta: 3      # 机器人的极限旋转加速度，单位为 rad/sec^2(robot's extreme rotation acceleration, unit:rad/sec^2)
  acc_lim_y: 0.0           # 机器人在y方向的极限加速度，对于差分机器人来说当然是0(robot's extreme acceleration along y direction. For differential robot, it is 0)
  
  # Goal Tolerance Parameters目标距离公差参数(Goal Tolerance Parameters)
  yaw_goal_tolerance: 0.05 # 到达目标点时，控制器在偏航/旋转时的弧度容差(tolerance)。即：到达目标点时偏行角允许的误差，单位弧度(radian tolerance of the controller when it is yawing and rotating and reaches target point, i.e. the allowable error of yaw angle when it reaches target point, unit: radian)
  xy_goal_tolerance: 0.17   # 到到目标点时，控制器在x和y方向上的容差（tolerence）（米）。即：到达目标点时,在xy平面内与目标点的距离误差(tolerance of the controller along x and y directions when reaching target point, i.e. the distance error between xy planes and target point, unit: meter)
  # latch_xy_goal_tolerance: false #设置为true时表示：如果到达容错距离内,机器人就会原地旋转；即使转动是会跑出容错距离外。(when it is set as true, it means that robot will rotate on the spot when reaching within the tolerence distance, though it can move to get out of tolerence distance)

  # Forward Simulation Parameters前向模拟参数(Forward Simulation Parameters)
  sim_time: 1.8       # 前向模拟轨迹的时间，单位为s(seconds) (time spent on forward simulating trajectory, unit: s(second))
  vx_samples: 10       # x方向速度空间的采样点数(number of sampling points in the x-direction velocity space)
  vy_samples: 0       # y方向速度空间采样点数.。差分驱动机器人y方向永远只有1个值（0.0）(number of sampling points in the y-direction velocity space. For differential robot, there is always single value,（0.0), in y direction)
  vtheta_samples: 20  # 旋转方向的速度空间采样点数(number of sampling points of velocity space in rotation direction)

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0      # 控制器与给定路径接近程度的权重(weight of how close the controller is to a given path)
  goal_distance_bias: 20.0       # 控制器与局部目标点的接近程度的权重，也用于速度控制(weight of how close the controller is to a local target point, which is used in velocity control)
  occdist_scale: 0.01             # 控制器躲避障碍物的程度(How well the controller avoids obstacles)
  forward_point_distance: 0.325  # 以机器人为中心，额外放置一个计分点的距离(centered on the robot, the distance of an additional scoring point is placed)
  stop_time_buffer: 0.2         # 机器人在碰撞发生前必须拥有的最少时间量。该时间内所采用的轨迹仍视为有效。即：为防止碰撞,机器人必须提前停止的时间长度(The minimum amount of time to leave before collision. Trajectories taken during this time are still valid. That is the time the robot must stop prematurely in order to prevent a collision)
  scaling_speed: 0.25             # 开始缩放机器人足迹时的速度的绝对值，单位为m/s。(the absolute value of velocity when robot's trajectory is scaled)
  max_scaling_factor: 0.2        # 最大缩放因子。max_scaling_factor为上式的值的大小。(maximum scaling factor. max_scaling_factor is the value of the above formula.)

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05   # 机器人必须运动多少米远后才能复位震荡标记(机器人运动多远距离才会重置振荡标记)(how long must the robot move before restoring oscillation mark)
  #oscillation_reset_angle: 0.05

  # Debugging调试参数(debugging parameters)
  publish_traj_pc : true       # 将规划的轨迹在RVIZ上进行可视化(visualize the planned trajectory on RVIZ)
  publish_cost_grid_pc: true   # 将代价值进行可视化显示(visualize the cost)
  global_frame_id: map         # 全局参考坐标系(local reference coordinate system)
