# 全局代价地图(global cost map)
global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 1
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  inflation_layer:
    enabled: true
    inflation_radius: 0.25 # 不能大于robot_radius, 全局规划时base_footprint与障碍物保持的最小距离, 小于此值则规划失败(cannot be greater than robot_radius. Minimum distance between base_footprint and obstacle during global planning. If it is less than this value, the planning ends in failure)
    cost_scaling_factor: 10.0 # 代价比例系数，越大则代价值越小, cost_scaling_factor越大占用的计算量越小(cost ratio factor. The greater it is, the less the cost is)
